### ISSUE TITLE
gcc argument order problem

### ISSUE THREAD

**Issue by jpellegrini** [SkF0023/Ncurses-Pong#1]
Hi.

Your Makefile calls gcc like this:
```
gcc -o pong -O2 -lncurses pong.c
```
This leads to several undefined reference errors on my machine, because you included `-lncurses` before `pong.c`.
This one works:
```
gcc -O2 pong.c -lncurses -o pong
```

Did the Makefile work for you? What is your setup?

**Comment by jpellegrini** [comment]
Also, it is considered good practice to add the `-Wall` option to gcc (enable all warnings), so you know when you've used something that is legal, although not good practice.

**Comment by skyler-ferrante** [comment]
Hello. I'm just about to change the make file to your suggestion. The makefile did work for me, I'm not sure why it worked for me but not you. My setup is just termux on a Chromebook how about you?

**Comment by jpellegrini** [comment]
Strange. It's gcc anyway...
But the new version works perfectly.

To understand why the other version failed on my computer, see this:
[Library order in static linking ](https://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking/)
gcc processes arguments in the order they are given.

I suppose you can close this issue. :)

**Comment by skyler-ferrante** [comment]
Yeah that is strange.
 Okay, I justed wanted to make sure it worked for you.
