### ISSUE TITLE
start ball at random location

### ISSUE THREAD

**Issue by jpellegrini** [SkF0023/Ncurses-Pong#2]
It would be nice if the ball started at a rando mlocation. Otherwise, the players will notice that they need to move the pads to the same places every game...

**Comment by skyler-ferrante** [comment]
I was thinking about instead having  ball_velocity_y be random instead. But the only problem is anything over 1 is too fast, and I can't seem to get it to work with decimals. If I set ball_velocity_y to a decimal the ball gets stuck on the walls.

**Comment by skyler-ferrante** [comment]
Just added it along with random direction
